[package]
name = "neoxide"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = { version = "0.28.1", features = ["event-stream"] }
futures = "0.3.30"
tokio = "1.39.3"
strum = "0.26"
strum_macros = "0.26"
rand = "0.8"
